In [11]:
# === ConvNeXt-Large (384) | Stratified 5-Fold OOF 평가 (train만 사용, test 없음) ===
from fastai.vision.all import *
from fastai.callback.tracker import SaveModelCallback, EarlyStoppingCallback
from timm import create_model
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, f1_score
from pathlib import Path
import numpy as np, pandas as pd, torch, random, gc

# -----------------------------
# 0) 기본 설정
# -----------------------------
SEED = 42
set_seed(SEED, reproducible=True)
try: torch.set_float32_matmul_precision('high')
except: pass

DATA_ROOT = Path('images/competition_training')   # ★ 네가 쓰던 학습 폴더
KNOWN_CLASSES = ['0','1','2','3','4']             # 클래스 고정
IMG_SIZE = 384
BS = 16
NUM_WORKERS = 8
EPOCHS = 12               # 네 기본 10에서 살짝 + (안정 수렴)
BASE_LR = 1e-4
PATIENCE = 4
N_FOLDS = 5               # 5-fold OOF
PREC = 4                  # 출력 소수점 자리

MODEL_NAME = 'convnext_large_in22k'
RUN_TAG = 'convnext_oof'  # 저장 파일 접두사

# -----------------------------
# 1) 데이터 목록/라벨 수집
# -----------------------------
items_all = get_image_files(DATA_ROOT, recurse=True)
labels_all = np.array([parent_label(p) for p in items_all])
assert set(labels_all).issubset(set(KNOWN_CLASSES)), "라벨이 KNOWN_CLASSES 밖에 있네요. 폴더 구조 확인!"

# -----------------------------
# 2) 유틸: 클래스 가중치 (훈련 파트에서만 계산)
# -----------------------------
def compute_class_weights_by_items(items, classes):
    cnt = {c:0 for c in classes}
    for p in items:
        c = parent_label(p)
        if c in cnt: cnt[c]+=1
    arr = np.array([max(1, cnt[c]) for c in classes], dtype=np.float32)
    inv = 1.0 / arr
    w = inv / inv.sum() * len(classes)  # 평균≈1 정규화
    return torch.tensor(w, dtype=torch.float32), cnt

# -----------------------------
# 3) OOF 준비 (예측/정답 저장)
# -----------------------------
oof_preds = np.empty(len(items_all), dtype=object)  # 예측 라벨 문자열
oof_true  = np.array([parent_label(p) for p in items_all], dtype=object)
oof_idx   = np.arange(len(items_all))

# -----------------------------
# 4) Stratified K-Fold 루프
# -----------------------------
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
fold_reports = []
for fold, (tr_idx, va_idx) in enumerate(skf.split(np.zeros(len(labels_all)), labels_all), 1):
    print(f"\n===== FOLD {fold}/{N_FOLDS} =====")
    train_items = [items_all[i] for i in tr_idx]
    valid_items = [items_all[i] for i in va_idx]

    class_weights, cnts = compute_class_weights_by_items(train_items, KNOWN_CLASSES)
    print(f"[fold {fold}] train counts = {cnts}")
    print(f"[fold {fold}] class weights = {class_weights.tolist()}")

    # DataBlock / DataLoaders (네 기본 증강 유지: Resize+aug_transforms)
    dblock = DataBlock(
        blocks=(ImageBlock, CategoryBlock(vocab=KNOWN_CLASSES)),
        get_items=lambda _: items_all,                  # 고정 리스트
        splitter=lambda _: (tr_idx.tolist(), va_idx.tolist()),
        get_y=parent_label,
        item_tfms=Resize(IMG_SIZE),
        batch_tfms=[*aug_transforms(size=IMG_SIZE),
                    Normalize.from_stats(*imagenet_stats)]
    )
    dls = dblock.dataloaders(None, bs=BS, num_workers=NUM_WORKERS, shuffle=True)

    # 모델/학습기
    n_out = len(KNOWN_CLASSES)
    model = create_model(MODEL_NAME, pretrained=True, num_classes=n_out)

    macro_f1 = F1Score(average='macro'); macro_f1.name = 'macro_f1'  # 모니터 이름 확정
    learn = Learner(
        dls,
        model,
        loss_func=CrossEntropyLossFlat(weight=class_weights.to(dls.device)),
        metrics=[macro_f1, accuracy],
        cbs=[
            SaveModelCallback(monitor='macro_f1', fname=f'{RUN_TAG}_fold{fold}_best'),
            EarlyStoppingCallback(monitor='macro_f1', patience=PATIENCE)
        ]
    ).to_fp16()

    # 학습
    learn.fine_tune(EPOCHS, base_lr=BASE_LR)

    # 베스트 로드 & 폴드 검증 평가
    learn.load(f'{RUN_TAG}_fold{fold}_best')
    val_loss, val_f1, val_acc = learn.validate()
    print(f"[fold {fold}] Val -> loss={float(val_loss):.{PREC}f}, F1(macro)={float(val_f1):.{PREC}f}, acc={float(val_acc):.{PREC}f}")

    # OOF 예측 저장
    with torch.no_grad():
        val_logits, _ = learn.get_preds(dl=dls.valid, with_decoded=False, act=None)
    val_pred_idx = val_logits.argmax(dim=1).cpu().numpy()
    idx2lbl = {i:c for i,c in enumerate(KNOWN_CLASSES)}
    val_pred_lbl = np.array([idx2lbl[i] for i in val_pred_idx], dtype=object)

    oof_preds[va_idx] = val_pred_lbl

    # 폴드 리포트
    report = classification_report(oof_true[va_idx], oof_preds[va_idx],
                                   target_names=KNOWN_CLASSES, digits=PREC, zero_division=0)
    print(f"\n[fold {fold}] OOF report\n{report}")
    fold_reports.append((fold, float(val_f1)))

    # 메모리 정리
    del learn, dls, model
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()

# -----------------------------
# 5) 전체 OOF 점수
# -----------------------------
oof_macro_f1 = f1_score(oof_true, oof_preds, average='macro', labels=KNOWN_CLASSES)
print("\n===== OOF SUMMARY =====")
for f, score in fold_reports:
    print(f"fold {f}: macro-F1={score:.{PREC}f}")
print(f"\nOOF macro-F1 = {oof_macro_f1:.{PREC}f}")

# OOF 리포트/CSV 저장
print("\n[OOF classification report]")
print(classification_report(oof_true, oof_preds, target_names=KNOWN_CLASSES, digits=PREC, zero_division=0))

oof_df = pd.DataFrame({
    'image': [items_all[i].relative_to(DATA_ROOT).as_posix() for i in range(len(items_all))],
    'true':  oof_true,
    'pred':  oof_preds
})
oof_df.to_csv('oof_pred_convnext_large_stratified.csv', index=False, encoding='utf-8-sig')
print("\nSaved: oof_pred_convnext_large_stratified.csv")

===== FOLD 1/5 =====
[fold 1] train counts = {'0': 4640, '1': 80, '2': 240, '3': 40, '4': 200}
[fold 1] class weights = [0.022984983399510384, 1.3331289291381836, 0.4443763494491577, 2.666257858276367, 0.5332515835762024]

/home/elicer/myenv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name convnext_large_in22k to current convnext_large.fb_in22k.
  model = create_fn(

Better model found at epoch 0 with macro_f1 value: 0.38660544273169667.

Better model found at epoch 0 with macro_f1 value: 0.5141283958798938.
Better model found at epoch 2 with macro_f1 value: 0.5572264930688636.
Better model found at epoch 5 with macro_f1 value: 0.5691071243900909.
Better model found at epoch 6 with macro_f1 value: 0.5776336540328046.
Better model found at epoch 7 with macro_f1 value: 0.5789703450639404.
Better model found at epoch 8 with macro_f1 value: 0.5941187685609026.

/home/elicer/myenv/lib/python3.12/site-packages/fastai/learner.py:59: UserWarning: Saved file doesn't contain an optimizer state.
  elif with_opt: warn("Saved file doesn't contain an optimizer state.")

Better model found at epoch 0 with macro_f1 value: 0.9323077201843262.
[fold 1] Val -> loss=0.3317, F1(macro)=0.5941, acc=0.9323

[fold 1] OOF report
              precision    recall  f1-score   support

           0     0.9645    0.9828    0.9735      1160
           1     0.1875    0.1500    0.1667        20
           2     0.5769    0.5000    0.5357        60
           3     0.6250    0.5000    0.5556        10
           4     0.8095    0.6800    0.7391        50

    accuracy                         0.9323      1300
   macro avg     0.6327    0.5626    0.5941      1300
weighted avg     0.9261    0.9323    0.9287      1300


===== FOLD 2/5 =====
[fold 2] train counts = {'0': 4640, '1': 80, '2': 240, '3': 40, '4': 200}
[fold 2] class weights = [0.022984983399510384, 1.3331289291381836, 0.4443763494491577, 2.666257858276367, 0.5332515835762024]

/home/elicer/myenv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name convnext_large_in22k to current convnext_large.fb_in22k.
  model = create_fn(

Better model found at epoch 0 with macro_f1 value: 0.3152790318397985.

Better model found at epoch 0 with macro_f1 value: 0.5222599020250646.
Better model found at epoch 1 with macro_f1 value: 0.5418342093478209.
Better model found at epoch 4 with macro_f1 value: 0.5516611709472522.
Better model found at epoch 6 with macro_f1 value: 0.5568422746422591.
Better model found at epoch 7 with macro_f1 value: 0.5878946162657502.
No improvement since epoch 7: early stopping

/home/elicer/myenv/lib/python3.12/site-packages/fastai/learner.py:59: UserWarning: Saved file doesn't contain an optimizer state.
  elif with_opt: warn("Saved file doesn't contain an optimizer state.")

Better model found at epoch 0 with macro_f1 value: 0.9215384721755981.
[fold 2] Val -> loss=0.3124, F1(macro)=0.5879, acc=0.9215

[fold 2] OOF report
              precision    recall  f1-score   support

           0     0.9606    0.9672    0.9639      1160
           1     0.2500    0.2000    0.2222        20
           2     0.5333    0.5333    0.5333        60
           3     0.6667    0.4000    0.5000        10
           4     0.7200    0.7200    0.7200        50

    accuracy                         0.9215      1300
   macro avg     0.6261    0.5641    0.5879      1300
weighted avg     0.9184    0.9215    0.9197      1300


===== FOLD 3/5 =====
[fold 3] train counts = {'0': 4640, '1': 80, '2': 240, '3': 40, '4': 200}
[fold 3] class weights = [0.022984983399510384, 1.3331289291381836, 0.4443763494491577, 2.666257858276367, 0.5332515835762024]

/home/elicer/myenv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name convnext_large_in22k to current convnext_large.fb_in22k.
  model = create_fn(

Better model found at epoch 0 with macro_f1 value: 0.3774715941735385.

Better model found at epoch 0 with macro_f1 value: 0.5427383496107512.
Better model found at epoch 1 with macro_f1 value: 0.5656186515697904.
No improvement since epoch 1: early stopping

/home/elicer/myenv/lib/python3.12/site-packages/fastai/learner.py:59: UserWarning: Saved file doesn't contain an optimizer state.
  elif with_opt: warn("Saved file doesn't contain an optimizer state.")

Better model found at epoch 0 with macro_f1 value: 0.9276922941207886.
[fold 3] Val -> loss=0.2498, F1(macro)=0.5656, acc=0.9277

[fold 3] OOF report
              precision    recall  f1-score   support

           0     0.9725    0.9750    0.9737      1160
           1     0.2857    0.1000    0.1481        20
           2     0.5500    0.3667    0.4400        60
           3     0.3704    1.0000    0.5405        10
           4     0.6508    0.8200    0.7257        50

    accuracy                         0.9277      1300
   macro avg     0.5659    0.6523    0.5656      1300
weighted avg     0.9254    0.9277    0.9235      1300


===== FOLD 4/5 =====
[fold 4] train counts = {'0': 4640, '1': 80, '2': 240, '3': 40, '4': 200}
[fold 4] class weights = [0.022984983399510384, 1.3331289291381836, 0.4443763494491577, 2.666257858276367, 0.5332515835762024]

/home/elicer/myenv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name convnext_large_in22k to current convnext_large.fb_in22k.
  model = create_fn(

Better model found at epoch 0 with macro_f1 value: 0.4848024123531454.

Better model found at epoch 0 with macro_f1 value: 0.5207308232054794.
Better model found at epoch 1 with macro_f1 value: 0.5619199338437852.
Better model found at epoch 3 with macro_f1 value: 0.5911003101691108.
Better model found at epoch 6 with macro_f1 value: 0.6059422760570823.
Better model found at epoch 8 with macro_f1 value: 0.6326312466627144.
Better model found at epoch 9 with macro_f1 value: 0.6413175369198638.
Better model found at epoch 10 with macro_f1 value: 0.6621408770637522.

/home/elicer/myenv/lib/python3.12/site-packages/fastai/learner.py:59: UserWarning: Saved file doesn't contain an optimizer state.
  elif with_opt: warn("Saved file doesn't contain an optimizer state.")

Better model found at epoch 0 with macro_f1 value: 0.936923086643219.
[fold 4] Val -> loss=0.2871, F1(macro)=0.6621, acc=0.9369

[fold 4] OOF report
              precision    recall  f1-score   support

           0     0.9733    0.9741    0.9737      1160
           1     0.4444    0.4000    0.4211        20
           2     0.5938    0.6333    0.6129        60
           3     0.6250    0.5000    0.5556        10
           4     0.7551    0.7400    0.7475        50

    accuracy                         0.9369      1300
   macro avg     0.6783    0.6495    0.6621      1300
weighted avg     0.9366    0.9369    0.9366      1300


===== FOLD 5/5 =====
[fold 5] train counts = {'0': 4640, '1': 80, '2': 240, '3': 40, '4': 200}
[fold 5] class weights = [0.022984983399510384, 1.3331289291381836, 0.4443763494491577, 2.666257858276367, 0.5332515835762024]

/home/elicer/myenv/lib/python3.12/site-packages/timm/models/_factory.py:138: UserWarning: Mapping deprecated model name convnext_large_in22k to current convnext_large.fb_in22k.
  model = create_fn(

Better model found at epoch 0 with macro_f1 value: 0.40497970323626475.

Better model found at epoch 0 with macro_f1 value: 0.5710226647664766.
No improvement since epoch 0: early stopping

/home/elicer/myenv/lib/python3.12/site-packages/fastai/learner.py:59: UserWarning: Saved file doesn't contain an optimizer state.
  elif with_opt: warn("Saved file doesn't contain an optimizer state.")

Better model found at epoch 0 with macro_f1 value: 0.8730769157409668.
[fold 5] Val -> loss=0.5196, F1(macro)=0.5710, acc=0.8731

[fold 5] OOF report
              precision    recall  f1-score   support

           0     0.9821    0.8991    0.9388      1160
           1     0.2800    0.3500    0.3111        20
           2     0.2923    0.6333    0.4000        60
           3     0.8000    0.4000    0.5333        10
           4     0.5513    0.8600    0.6719        50

    accuracy                         0.8731      1300
   macro avg     0.5811    0.6285    0.5710      1300
weighted avg     0.9215    0.8731    0.8909      1300


===== OOF SUMMARY =====
fold 1: macro-F1=0.5941
fold 2: macro-F1=0.5879
fold 3: macro-F1=0.5656
fold 4: macro-F1=0.6621
fold 5: macro-F1=0.5710

OOF macro-F1 = 0.5961

[OOF classification report]
              precision    recall  f1-score   support

           0     0.9704    0.9597    0.9650      5800
           1     0.2927    0.2400    0.2637       100
           2     0.4624    0.5333    0.4954       300
           3     0.5185    0.5600    0.5385        50
           4     0.6773    0.7640    0.7180       250

    accuracy                         0.9183      6500
   macro avg     0.5843    0.6114    0.5961      6500
weighted avg     0.9217    0.9183    0.9197      6500


Saved: oof_pred_convnext_large_stratified.csv